from flask import Request, Flask
from firebase import firebase
from model import Invoice
import pyrebase
import json
from flask import *
import string
import random
DATABASE = firebase.FirebaseApplication('https://csc207-tli.firebaseio.com/',
                                        None)
DATABASE.put("Truck Driver/nSTFFgWdZvYpenarvvTmpXxJIYA3/" + "Assigned Invoices", "invoice189898", "djfwejr23")
tinyUrlDictionary = {"https://tinyurl.com/": "http://www.amazon.com/Kindle-Wireless-Reading-Display-Globally/dp/B003FSUDM4/ref=amb_link_353259562_2?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=center-10&pf_rd_r=11EYKTN682A79T370AM3&pf_rd_t=201&pf_rd_p=1270985982&pf_rd_i=B002Y27P3M"}

def autogenerateDict(big_url: str):
    newTinyUrl = "https://tinyurl.com/"
    while newTinyUrl in tinyUrlDictionary:
        newTinyUrl += random.choice(string.ascii_letters)
    tinyUrlDictionary[newTinyUrl] = big_url
    return "Finished autogeneration."

def tinyUrlToBigUrl(tiny_url: str):
    if tiny_url in tinyUrlDictionary:
        return tinyUrlDictionary[tiny_url]
    else:
        return "No such url exists."
def bigUrltoTinyUrl(big_url: str):
    for key in tinyUrlDictionary:
        if(tinyUrlDictionary[key] == big_url.strip()):
            return key
    return "No such url exists."
if __name__ == '__main__':
    print(autogenerateDict("http://www.amazon.com/Kindle-Wireless-Reading-Display-Globally/dp/B003FSUDM4/ref=amb"))
    print(bigUrltoTinyUrl("http://www.amazon.com/Kindle-Wireless-Reading-Display-Globally/dp/B003FSUDM4/ref=amb"))
    print(tinyUrlToBigUrl(bigUrltoTinyUrl("http://www.amazon.com/Kindle-Wireless-Reading-Display-Globally/dp/B003FSUDM4/ref=amb")))
    print(tinyUrlDictionary)